### ISSUE TITLE
Let other Slack workspaces use this too

### ISSUE THREAD

**Issue by quackduck** [cjdenio/emojimage#1]
https://github.com/cjdenio/emojimage/blob/master/init/init.go#L79 makes it so it's Hack Club specific, if I understand correctly.

**Comment by cjdenio** [comment]
Thanks! I think the `hackclub.` prefix is just a proxy to prevent CORS issues, but it's good to be safe

**Comment by quackduck** [comment]
Wait, how does slack know which workspace to put the url in? I thought you'd have a way to make that prefix configurable.

**Comment by cjdenio** [comment]
It does it based on the token's origin (just like the regular API); every token belongs to a specific workspace

**Comment by quackduck** [comment]
Cool!
